<b> Installing Pytorch </b>

In [3]:
# !conda install -c soumith pytorch -y

In [1]:
import torch
import numpy as np

# Tensors

Create a tensor of size (4 x 6) :

In [2]:
a_np = np.ones((4,6))

In [3]:
torch.ones(4,6)


 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
[torch.FloatTensor of size 4x6]

In [4]:
torch.zeros(4,6)


 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
[torch.FloatTensor of size 4x6]

In [5]:
a = torch.FloatTensor(3,5)

In [6]:
a.fill_(5.)


 5  5  5  5  5
 5  5  5  5  5
 5  5  5  5  5
[torch.FloatTensor of size 3x5]

In [7]:
b = torch.zeros(4,6)
b.fill_(6)


 6  6  6  6  6  6
 6  6  6  6  6  6
 6  6  6  6  6  6
 6  6  6  6  6  6
[torch.FloatTensor of size 4x6]

In [8]:
b


 6  6  6  6  6  6
 6  6  6  6  6  6
 6  6  6  6  6  6
 6  6  6  6  6  6
[torch.FloatTensor of size 4x6]

In [9]:
a_np + 1

array([[ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.]])

<b> In-place/ out-of-place operations </b>

In [10]:
b.div(7)


 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
[torch.FloatTensor of size 4x6]

In [11]:
b


 6  6  6  6  6  6
 6  6  6  6  6  6
 6  6  6  6  6  6
 6  6  6  6  6  6
[torch.FloatTensor of size 4x6]

In [12]:
b.div_(7)


 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
[torch.FloatTensor of size 4x6]

In [13]:
b


 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
[torch.FloatTensor of size 4x6]

In [14]:
b.mul(3)


 2.5714  2.5714  2.5714  2.5714  2.5714  2.5714
 2.5714  2.5714  2.5714  2.5714  2.5714  2.5714
 2.5714  2.5714  2.5714  2.5714  2.5714  2.5714
 2.5714  2.5714  2.5714  2.5714  2.5714  2.5714
[torch.FloatTensor of size 4x6]

In [15]:
b.add(10.5)


 11.3571  11.3571  11.3571  11.3571  11.3571  11.3571
 11.3571  11.3571  11.3571  11.3571  11.3571  11.3571
 11.3571  11.3571  11.3571  11.3571  11.3571  11.3571
 11.3571  11.3571  11.3571  11.3571  11.3571  11.3571
[torch.FloatTensor of size 4x6]

In [16]:
b.sub(2)


-1.1429 -1.1429 -1.1429 -1.1429 -1.1429 -1.1429
-1.1429 -1.1429 -1.1429 -1.1429 -1.1429 -1.1429
-1.1429 -1.1429 -1.1429 -1.1429 -1.1429 -1.1429
-1.1429 -1.1429 -1.1429 -1.1429 -1.1429 -1.1429
[torch.FloatTensor of size 4x6]

In [17]:
b.transpose(0,1)


 0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571
[torch.FloatTensor of size 6x4]

In [18]:
c = torch.rand(3,4)

In [19]:
c


 0.0874  0.9883  0.3925  0.4450
 0.9754  0.7935  0.2538  0.9031
 0.5353  0.5305  0.5907  0.2758
[torch.FloatTensor of size 3x4]

In [20]:
c.min()

0.0873919129371643

In [21]:
c.max()

0.9883310794830322

In [22]:
c.mean()

0.5642791489760081

In [23]:
c.sum()

6.771349787712097

In [24]:
c.sum(0)


 1.5981
 2.3124
 1.2370
 1.6239
[torch.FloatTensor of size 4]

In [25]:
c.sum(1)


 1.9132
 2.9258
 1.9323
[torch.FloatTensor of size 3]

<b> Passing by reference/value </b>

In [26]:
a = b

In [27]:
a


 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
 0.8571  0.8571  0.8571  0.8571  0.8571  0.8571
[torch.FloatTensor of size 4x6]

In [28]:
a.add_(2)


 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
[torch.FloatTensor of size 4x6]

In [29]:
b


 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
[torch.FloatTensor of size 4x6]

In [30]:
a = a.add(2)

In [31]:
a


 4.8571  4.8571  4.8571  4.8571  4.8571  4.8571
 4.8571  4.8571  4.8571  4.8571  4.8571  4.8571
 4.8571  4.8571  4.8571  4.8571  4.8571  4.8571
 4.8571  4.8571  4.8571  4.8571  4.8571  4.8571
[torch.FloatTensor of size 4x6]

In [32]:
b


 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
[torch.FloatTensor of size 4x6]

In [33]:
c = torch.FloatTensor(4,6)

In [34]:
c.copy_(b)


 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
[torch.FloatTensor of size 4x6]

In [35]:
c.mul_(23)


 65.7143  65.7143  65.7143  65.7143  65.7143  65.7143
 65.7143  65.7143  65.7143  65.7143  65.7143  65.7143
 65.7143  65.7143  65.7143  65.7143  65.7143  65.7143
 65.7143  65.7143  65.7143  65.7143  65.7143  65.7143
[torch.FloatTensor of size 4x6]

In [36]:
b


 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
 2.8571  2.8571  2.8571  2.8571  2.8571  2.8571
[torch.FloatTensor of size 4x6]

<b> Indexing and slicing </b>

In [37]:
b[0,2]

2.857142925262451

In [38]:
b[:,1]  = 5

In [39]:
b


 2.8571  5.0000  2.8571  2.8571  2.8571  2.8571
 2.8571  5.0000  2.8571  2.8571  2.8571  2.8571
 2.8571  5.0000  2.8571  2.8571  2.8571  2.8571
 2.8571  5.0000  2.8571  2.8571  2.8571  2.8571
[torch.FloatTensor of size 4x6]

In [40]:
b[1:3,2:4] = 10

In [41]:
b


  2.8571   5.0000   2.8571   2.8571   2.8571   2.8571
  2.8571   5.0000  10.0000  10.0000   2.8571   2.8571
  2.8571   5.0000  10.0000  10.0000   2.8571   2.8571
  2.8571   5.0000   2.8571   2.8571   2.8571   2.8571
[torch.FloatTensor of size 4x6]

<b> Numpy array <-> Torch tensor </b>

In [42]:
type(b)

torch.FloatTensor

In [43]:
b_np = b.numpy()

In [44]:
b_np

array([[  2.85714293,   5.        ,   2.85714293,   2.85714293,
          2.85714293,   2.85714293],
       [  2.85714293,   5.        ,  10.        ,  10.        ,
          2.85714293,   2.85714293],
       [  2.85714293,   5.        ,  10.        ,  10.        ,
          2.85714293,   2.85714293],
       [  2.85714293,   5.        ,   2.85714293,   2.85714293,
          2.85714293,   2.85714293]], dtype=float32)

In [45]:
torch.from_numpy(a_np)


 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
[torch.DoubleTensor of size 4x6]

In [46]:
a_np.shape[0]

4

In [47]:
a.size()[0]

4

<b> Matrix multiplication </b>

In [48]:
a = torch.ones(4,6)
b = torch.ones(6,5)

In [49]:
a.mm(b)


 6  6  6  6  6
 6  6  6  6  6
 6  6  6  6  6
 6  6  6  6  6
[torch.FloatTensor of size 4x5]

In [50]:
a_np = a.numpy()
b_np = b.numpy()

In [51]:
a_np.dot(b_np)

array([[ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.]], dtype=float32)

<b> Element-wise matrix operations </b>

In [52]:
a = torch.ones(4,6)
b = torch.ones(4,6)

In [53]:
a.fill_(5)
b.fill_(2)


 2  2  2  2  2  2
 2  2  2  2  2  2
 2  2  2  2  2  2
 2  2  2  2  2  2
[torch.FloatTensor of size 4x6]

In [54]:
a + b


 7  7  7  7  7  7
 7  7  7  7  7  7
 7  7  7  7  7  7
 7  7  7  7  7  7
[torch.FloatTensor of size 4x6]

In [55]:
a - b


 3  3  3  3  3  3
 3  3  3  3  3  3
 3  3  3  3  3  3
 3  3  3  3  3  3
[torch.FloatTensor of size 4x6]

In [56]:
a * b


 10  10  10  10  10  10
 10  10  10  10  10  10
 10  10  10  10  10  10
 10  10  10  10  10  10
[torch.FloatTensor of size 4x6]

In [57]:
a / b 


 2.5000  2.5000  2.5000  2.5000  2.5000  2.5000
 2.5000  2.5000  2.5000  2.5000  2.5000  2.5000
 2.5000  2.5000  2.5000  2.5000  2.5000  2.5000
 2.5000  2.5000  2.5000  2.5000  2.5000  2.5000
[torch.FloatTensor of size 4x6]

<b> View function </b>

In [58]:
a = torch.range(1,12)
a.view(2, 6)

/Users/A/Softwares/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.3. Note that arange generates values in [start; end), not [start; end].
  if __name__ == '__main__':



  1   2   3   4   5   6
  7   8   9  10  11  12
[torch.FloatTensor of size 2x6]

In [59]:
torch.range(1,12).view(2,6)

/Users/A/Softwares/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.3. Note that arange generates values in [start; end), not [start; end].
  if __name__ == '__main__':



  1   2   3   4   5   6
  7   8   9  10  11  12
[torch.FloatTensor of size 2x6]

In [60]:
a


  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
[torch.FloatTensor of size 12]

In [61]:
a.view(4, 3)


  1   2   3
  4   5   6
  7   8   9
 10  11  12
[torch.FloatTensor of size 4x3]

In [62]:
a.view(3, -1)


  1   2   3   4
  5   6   7   8
  9  10  11  12
[torch.FloatTensor of size 3x4]

In [63]:
a.view(-1,4)


  1   2   3   4
  5   6   7   8
  9  10  11  12
[torch.FloatTensor of size 3x4]

In [64]:
a.size()

torch.Size([12])

In [65]:
a


  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
[torch.FloatTensor of size 12]

In [66]:
a.unsqueeze(0)  # reshape()


    1     2     3     4     5     6     7     8     9    10    11    12
[torch.FloatTensor of size 1x12]

In [67]:
a.unsqueeze(1)


    1
    2
    3
    4
    5
    6
    7
    8
    9
   10
   11
   12
[torch.FloatTensor of size 12x1]

In [68]:
b = a.unsqueeze(0)

In [69]:
b


    1     2     3     4     5     6     7     8     9    10    11    12
[torch.FloatTensor of size 1x12]

In [70]:
b.squeeze()


  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
[torch.FloatTensor of size 12]